<<<<<<< HEAD
=======
<<<<<<< HEAD
>>>>>>> main
- id: doi:10.15252/msb.20178124
  description: MOFA is a factor analysis model that provides a general framework for the integration of multi-omic data sets in an unsupervised fashion
  image: https://www.embopress.org/cms/10.15252/msb.20178124/asset/38d5fe53-2af9-469a-a44c-399133a490df/assets/graphic/msb178124-abs-0001-m.png
  date: '2018-06-18'
  buttons:
    - type: MOFA webpage
      link: https://biofam.github.io/MOFA2/index.html
  tags:
    - multi-modal data integration
    - probabilistic factor models
- id: doi:10.1038/s41592-021-01343-9
  description: MEFISTO is a unsupervised method to integrate multi-modal data with continuous structures among the samples, e.g. in spatial or temporal data.
  image: https://biofam.github.io/MOFA2/images/mefisto.png
  buttons:
    - type: MEFISTO webpage
      link: https://biofam.github.io/MOFA2/MEFISTO.html
  tags:
    - multi-modal data integration
    - probabilistic factor models
    - spatio-temporal models
- id: doi:10.1093/bioinformatics/btad183
  description: FISHFactor identifies spatial gene expression patterns at subcellular resolution
  image: https://github.com/bioFAM/FISHFactor/raw/master/model.png
  buttons:
    - type: GitHub webpage
      link: https://github.com/bioFAM/FISHFactor
  tags:
    - probabilistic factor models
    - spatial models
<<<<<<< HEAD
=======
=======
- id: doi:10.1371/journal.pcbi.1007128
  type: paper
  description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
  date: 2020-12-4
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
  buttons:
    - type: manubot
      link: https://greenelab.github.io/meta-review/
    - type: source
      text: Manuscript Source
      link: https://github.com/greenelab/meta-review
    - type: website
      link: http://manubot.org/
  tags:
    - open science
    - collaboration
  repo: greenelab/meta-review

- id: doi:10.1016/j.csbj.2020.05.017
  image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

- id: doi:10.7554/eLife.32822
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
>>>>>>> template/main
>>>>>>> main
